language: ruby
notifications:
  email:
    - parndt@gmail.com
script: bundle exec rspec spec
env:
  - DB=sqlite3
  - DB=sqlite3mem
  - DB=postgresql
  - DB=mysql
rvm:
  - 2.0.0
  - 1.9.3
  - rbx-19mode
  - jruby-19mode
